import type { Metadata } from "next";
import { Inter, Nunito, Poppins } from "next/font/google";
import "./globals.css";
import "./embla.css";
import Wrapper from "./wrapper";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";

// const inter = Nunito({ subsets: ['latin'], weight: ["200", "300", "400", "500", "600", "700", "800", "900"] })
const inter = Poppins({ subsets: ['latin'], weight: ["200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Wrapper session={session}>
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
